name: Test Control Plane

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: ${{ matrix.ruby }} with ${{ matrix.discovery.name }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        os:
          - ubuntu

        ruby:
          - "3.3"
          - "3.4"
          - "4.0"

        discovery:
          - name: CDS and EDS
            publish_clusters: "true"
            envoy_config: ./envoy.yaml
          - name: EDS only
            publish_clusters: "false"
            envoy_config: ./envoy-eds.yaml

        experimental: [false]

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      timeout-minutes: 10
      env:
        RUBY_VERSION: ${{ matrix.ruby }}
        PUBLISH_CLUSTERS: ${{ matrix.discovery.publish_clusters }}
        ENVOY_CONFIG: ${{ matrix.discovery.envoy_config }}
      run: docker compose -f control-plane/docker-compose.yaml up --build --exit-code-from tests
